server:
    port: 8080
    ssl:
        key-password: ldp-services-key-secret
        key-store: file:///security/keystore.jks
        key-store-password: ldp-services-keystore-secret
    context-path: /dataservice/decisions/
spring.jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
        hibernate.default_schema: msj_a2591_production
spring.datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://testpostgresdms.c87yjuezj1dy.us-west-2.rds.amazonaws.com/testpostgres
    username: testuser
    password: testuser
