server:
    port: 8080
    ssl:
        key-password: ldp-services-key-secret
        key-store: file:///security/keystore.jks
        key-store-password: ldp-services-keystore-secret
    context-path: /dataservice/decisions/
spring.jpa:
    database: testpostgres
    show-sql: true
    hibernate.ddl-auto: create-drop
spring.datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:testpostgresdms.c87yjuezj1dy.us-west-2.rds.amazonaws.com
    username: testuser
    password: testuser


