server:
    port: 8080
    context-path: /dataservice/decisions/
spring.jpa:
    database: POSTGRESSQL
    show-sql: true
    hibernate.ddl-auto: create-drop
spring.datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: testpostgresdms.c87yjuezj1dy.us-west-2.rds.amazonaws.com
    username: testuser
    password: testuser
