/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.lumeris.dataplatform.dataservice.decisions.api.api;

import java.util.List;

import javax.validation.constraints.NotNull;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.lumeris.dataplatform.dataservice.decisions.api.models.PatientDetails;
import com.lumeris.dataplatform.dataservice.decisions.api.models.PatientRosterItem;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-01-09T19:49:40.625Z")

@Api(value = "v1", description = "the v1 API")
public interface V1Api {

    @ApiOperation(value = "Produces Patient Roster document with list of Extracts and Risk Models for the provided client and patient Id.", notes = "Produces Patient Roster document with list of Extracts and Risk Models for the provided client and patient Id.", response = PatientDetails.class, tags={ "decisions-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = PatientDetails.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Void.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Void.class),
        @ApiResponse(code = 404, message = "Not Found", response = Void.class),
        @ApiResponse(code = 500, message = "Server error", response = Void.class) })
    
    @RequestMapping(value = "/v1/patientDetails",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<PatientDetails> getPatientDetailsByIdUsingGET( @NotNull@ApiParam(value = "Full Name of the patient where patient-name starts with provided value.", required = true) @RequestParam(value = "patientid", required = true) String patientid);


    @ApiOperation(value = "Produces Patient Roster document with list of Extracts and Risk Models for the provided client and patient Id.", notes = "Produces Patient Roster document with list of Extracts and Risk Models for the provided client and patient Id.", response = PatientRosterItem.class, responseContainer = "List", tags={ "decisions-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = PatientRosterItem.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized", response = Void.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Void.class),
        @ApiResponse(code = 404, message = "Not Found", response = Void.class),
        @ApiResponse(code = 500, message = "Server error", response = Void.class) })
    
    @RequestMapping(value = "/v1/patientRoster",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<PatientRosterItem>> getPatientRosterSummaryUsingGET();

}
